Repository function-future/function-frontend, pull requests merged in 2020-01, with the labels that each got.

#219 Fix nginx conf
  nginx/conf/nginx.conf
Labels: bug

#220 Feature/deployment prep
  package-lock.json
  package.json
  server.js
  static.json
Labels: enhancement

#229 Bugfix/remove vue toasted
  src/router/index.js
  src/views/Assignment/StudentAssignments.vue
  src/views/Assignment/js/student-assignments.js
  src/views/FinalJudging/js/report-page.js
  src/views/QuestionBank/js/question-bank-detail.js
  src/views/QuestionBank/js/question-bank-form.js
  src/views/QuestionBank/js/question-form.js
  src/views/Quiz/StudentQuizDetail.vue
  src/views/Quiz/js/quiz-questions.js
  src/views/Quiz/js/student-quiz-detail.js
  tests/unit/specs/views/Assignments/StudentAssignments.spec.js
  tests/unit/specs/views/FinalJudging/ReportPage.spec.js
  tests/unit/specs/views/QuestionBank/QuestionBankDetail.spec.js
  tests/unit/specs/views/QuestionBank/QuestionBankForm.spec.js
  tests/unit/specs/views/QuestionBank/QuestionForm.spec.js
  tests/unit/specs/views/Quiz/StudentQuizDetail.spec.js
Labels: bug

#228 Bugfix/assignment files
  src/views/Assignment/js/assignment-form.js
  src/views/Quiz/js/quiz-form.js
  tests/unit/specs/views/Assignments/AssignmentForm.spec.js
Labels: bug

#231 Added emptyState to points page
  src/views/Point/Point.vue
  src/views/Point/js/point.js
  tests/unit/specs/views/Point/Point.spec.js
Labels: bug

#235 Bugfix
  src/components/modals/js/modal-select-multiple-students.js
  src/components/modals/js/modal-select-question-bank.js
  src/components/skeletons/BottomNavBar.vue
  src/router/index.js
  src/views/Assignment/StudentAssignments.vue
  src/views/Assignment/js/assignment-room-detail.js
  src/views/Assignment/js/student-assignments.js
  src/views/Feeds/FeedsRevamp.vue
  src/views/FinalJudging/JudgingList.vue
  src/views/FinalJudging/js/report-page.js
  src/views/QuestionBank/QuestionBankQuestionDetail.vue
  src/views/QuestionBank/js/question-bank-form.js
  src/views/QuestionBank/js/question-form.js
  src/views/Quiz/StudentQuizDetail.vue
  src/views/Quiz/js/student-quiz-detail.js
  src/views/Scoring/LandingPageAdmin.vue
  tests/unit/specs/views/Assignments/StudentAssignments.spec.js
  tests/unit/specs/views/FinalJudging/ReportPage.spec.js
  tests/unit/specs/views/QuestionBank/QuestionBankForm.spec.js
  tests/unit/specs/views/QuestionBank/QuestionForm.spec.js
  tests/unit/specs/views/Quiz/StudentQuizDetail.spec.js
Labels: bug, unit-test

#239 Feature/improve load time
  .babelrc
  nginx/conf/nginx.conf
  package-lock.json
  package.json
  src/router/index.js
  static.json
  vue.config.js
Labels: enhancement

#245 Fixed prefetch chunk for faster load
  vue.config.js
Labels: bug

#246 Added early nginx config for websocket
  nginx/conf/nginx.conf
  static.json
Labels: bug
